"""Add review_nums and ensure rating exists

Revision ID: 223677a9a3c4
Revises: 801fdacb71bb
Create Date: 2026-01-25 12:07:19.578723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223677a9a3c4'
down_revision = '801fdacb71bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('review_nums', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('review_nums')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
